title: "UPCAST Training Portal"
description: "A training platform for the UPCAST Project."

# Your GitHub Pages domain
url: "https://pankajbadatia.github.io"

# MUST match repository name exactly
baseurl: "/upcast-training-portal"

# Use Jekyll default theme (you override with your own HTML anyway)
theme: minima

# GitHub Pages supported plugins only
plugins:
  - jekyll-feed
  - jekyll-seo-tag

