title: UPCAST Training
description: A training blog for upcast Project
baseurl: "/blog" # No subpath for GitHub Pages root repository
url: "https://pankajbadatia.github.io"
theme: minima
plugins:
  - jekyll-paginate
paginate: 10 # Number of posts per page
paginate_path: "/page:num/"
